+incdir+src
+incdir+tb
src/ifq.v
src/icache.v
src/dispatch.v
src/regfile.v
src/reg_status_table.v
src/reg_status_table_mem.v
src/tagfifo.v
src/equeueint.v
src/equeuemult.v
src/equeuediv.v
src/equeuels.v
src/cpu.v
tb/tb_top.v
